### ISSUE TITLE
Are the gorm model tags added manually?

### ISSUE THREAD

**Issue by jacobblock** [anselm94/googlekeepclone#2]
Been reading through the code and saw the `models_gen.go` has gorm tags. Were these added to the generated code manually? I don't see what would add these in the repo, but figured I'd ask since there is also some effort for this kind of feature in other places:

* [gqlgen's modelgen-hook](https://gqlgen.com/recipes/modelgen-hook/)
* This recent [PR](https://github.com/99designs/gqlgen/pull/1173) for adding an `extraTag` directive.

And thanks for the nice project; definitely helped me learn a few things.

**Comment by anselm94** [comment]
hi @jacobblock, yes. The GORM tags were added manually over the generated `models_gen.go`. I had to take a backup of this file, whenever I needed to update the GraphQL Schema and then re-apply the backed-up file. Thanks for the pointers:smile:
