### ISSUE TITLE
Unable to launch it in Dubug mode

### ISSUE THREAD

**Issue by dragonblood** [anselm94/googlekeepclone#4]
Start the Go server in Debug mode. See launch.json
      Go to 'Run' -> 'Launch Go API server'

Results in:

```
go: github.com/matoous/go-nanoid@v1.1.0: parsing go.mod: go.mod:1: invalid go version '1.12.3': must match format 1.23
exit status 1
Process exiting with code: 1
```

**Comment by anselm94** [comment]
@dragonblood Thanks for reporting. This project has now been updated to the latest Golang 1.16 and this issue is resolved.
https://github.com/anselm94/googlekeepclone/blob/5be41ada8f06d71db3cc3d535b586d911604893b/go.mod#L3
