### ISSUE TITLE
main.go not found

### ISSUE THREAD

**Issue by patoniilista** [anselm94/googlekeepclone#6]
Hi. In the step 4 from the manual method I can't seem to make it work. The readme says
> cd ..
> EXPORT PORT=8080
> EXPORT STATIC_DIR=/web/build
> EXPORT DB_FILE=keepclone.db
> EXPORT COOKIE_STORE_KEY=$(uuidgen | base64)
> EXPORT SESSION_STORE_KEY=$(uuidgen | base64)
> go run server/main.go

But when I type `go run server/main.go`, it says that there's no main.go in the server folder. I've tested it on an Arch Linux machine and even on Windows 10, no luck. Also tried to build and install multiple times, and still no main.go.

Could it be some dependency, even though it builds without any error besides out of date packages?

**Comment by anselm94** [comment]
@patoniilista sorry for the inconvenience. It should be `go run ./cmd/server/main.go`. Now, this has been updated in the [README.md](https://github.com/anselm94/googlekeepclone/blob/master/README.md#L209). Thanks for reporting.
